services:
  yphf.statistics.service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - RetryMigrations=true
      - Port=8110
    ports:
      - "8110:80"
      - "8115:50001"
    volumes:
      - "./logs/:/app/logs"