services:
  redis:
    command: redis-server --requirepass 123456
    ports:
      - "6379:6379"

  consul:
    ports:
      - "8500:8500"
    command: agent -dev -client=0.0.0.0

  zipkin:
    ports:
      - "9411:9411"

  yphf.airspace.service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - RetryMigrations=true
      - Port=8000
    ports:
      - "8000:80"
      - "8005:50001"
    volumes:
      - "./logs/:/app/logs"

  yphf.auth.service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - RetryMigrations=true
      - Port=8010
    ports:
      - "8010:80"
      - "8015:50001"
    volumes:
      - "./logs/:/app/logs"

  yphf.basic.service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - RetryMigrations=true
      - Port=8020
    ports:
      - "8020:80"
      - "8025:50001"
    volumes:
      - "./logs/:/app/logs"

  yphf.events.services:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - RetryMigrations=true
      - Port=8030
    ports:
      - "8030:80"
      - "8035:50001"
    volumes:
      - "./logs/:/app/logs"

  yphf.files.service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - RetryMigrations=true
      - Port=8040
    ports:
      - "8040:80"
      - "8045:50001"
    volumes:
      - "./logs/:/app/logs"

  yphf.gateway.service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - RetryMigrations=true
      - Port=7000
    ports:
      - "7000:80"
      - "7005:50001"
    volumes:
      - "./logs/:/app/logs"

  yphf.gen.service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - RetryMigrations=true
      - Port=8050
    ports:
      - "8050:80"
      - "8055:50001"
    volumes:
      - "./logs/:/app/logs"

  yphf.gov.service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - RetryMigrations=true
      - Port=8060
    ports:
      - "8060:80"
      - "8065:50001"
    volumes:
      - "./logs/:/app/logs"

  yphf.job.service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - RetryMigrations=true
      - Port=8070
    ports:
      - "8070:80"
      - "8075:50001"
    volumes:
      - "./logs/:/app/logs"

  yphf.plan.service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - RetryMigrations=true
      - Port=8080
    ports:
      - "8080:80"
      - "8085:50001"
    volumes:
      - "./logs/:/app/logs"

  yphf.push.service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - RetryMigrations=true
      - Port=8090
    ports:
      - "8090:80"
      - "8095:50001"
    volumes:
      - "./logs/:/app/logs"

  yphf.signal.service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - RetryMigrations=true
      - Port=8100
    ports:
      - "8100:80"
      - "8105:50001"
    volumes:
      - "./logs/:/app/logs"

  yphf.statistics.service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - RetryMigrations=true
      - Port=8110
    ports:
      - "8110:80"
      - "8115:50001"
    volumes:
      - "./logs/:/app/logs"

  yphf.weather.service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - RetryMigrations=true
      - Port=8120
    ports:
      - "8120:80"
      - "8125:50001"
    volumes:
      - "./logs/:/app/logs"