services:
  redis:
    command: redis-server --requirepass 123456
    ports:
      - "6379:6379"

  consul:
    ports:
      - "8500:8500"
    command: agent -dev -client=0.0.0.0

  zipkin:
    ports:
      - "9411:9411"

  dapr-placement:
    command: ["./placement", "-port", "50000", "-log-level", "debug"]
    ports:
      - "50000:50000"