services:
  vitecent.job.service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - RetryMigrations=true
      - Port=8070
    ports:
      - "8070:80"
      - "8075:50001"
    volumes:
      - "./Logs/:/app/Logs"