services:
  yphf.gateway.service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - RetryMigrations=true
      - Port=7000
    ports:
      - "7000:80"
      - "7005:50001"
    volumes:
      - "./Logs/:/app/Logs"