services:
  yphf.files.service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - RetryMigrations=true
      - Port=8040
    ports:
      - "8040:80"
      - "8045:50001"
    volumes:
      - "./Logs/:/app/Logs"