apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: ViteCent-statestore
  namespace: ViteCent
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: 192.168.0.53:6379
  - name: redisPassword
    value: "123456"
  - name: actorStateStore
    value: "true"
