services:
  yphf.gen.service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - RetryMigrations=true
      - Port=8050
    ports:
      - "8050:80"
      - "8055:50001"
    volumes:
      - "./logs/:/app/logs"