services:
  yphf.weather.service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - RetryMigrations=true
      - Port=8120
    ports:
      - "8120:80"
      - "8125:50001"
    volumes:
      - "./logs/:/app/logs"