services:
  yphf.basic.service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - RetryMigrations=true
      - Port=8020
    ports:
      - "8020:80"
      - "8025:50001"