services:
  yphf.airspace.service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - RetryMigrations=true
      - Port=8000
    ports:
      - "8000:80"
      - "8005:50001"
    volumes:
      - "./logs/:/app/logs"